function []=plotmlpmd()
    a =[84.77,0.6;
        84.63,0.63];
    model=[1,2,3,4];
    subplot(1,3,1);
    figure(1),plot(1,82,'ko','color','white');hold on;
    figure(1),plot(2,a(1,1),' ko','MarkerSize',10,'MarkerFacecolor','black');
    figure(1),plot(3,a(2,1),'ko','MarkerSize',10,'MarkerFacecolor',[0.5,0.5,0.5]);
    figure(1),plot(4,82,'ko','color','white');
    er=errorbar([2,3],a(:,1),a(:,2),a(:,2));
    er.Color=[1 0 0];
    er.LineWidth=2;
    er.LineStyle='none';
    % XTick([1:1:2]);
    set(gca,'xtick',[1:1:4],'XTickLabel',{'','Train','Test'});
    ylabel('Accuracy [%]','fontsize',18,'fontweight','normal','fontname','Times New Roman');
    set(gca,'fontsize',15);
    % xtickangle(45);
    ylim([58 86]);
    % legend('','Train','Test');
    title(gca,'MLP_1','FontWeight','normal');
    hold off;

    a=[82.23,1.06;81.71,0.77];
    subplot(1,3,2);
    figure(1),plot(1,82,'ko','color','white');hold on;
    figure(1),plot(2,a(1,1),' ko','MarkerSize',10,'MarkerFacecolor','black');
    figure(1),plot(3,a(2,1),'ko','MarkerSize',10,'MarkerFacecolor',[0.5,0.5,0.5]);
    figure(1),plot(4,82,'ko','color','white');
    er=errorbar([2,3],a(:,1),a(:,2),a(:,2));
    er.Color=[1 0 0];
    er.LineWidth=2;
    er.LineStyle='none';
    % XTick([1:1:2]);
    set(gca,'xtick',[1:1:4],'XTickLabel',{'','Train','Test'});
    ylabel('Accuracy [%]','fontsize',18,'fontweight','normal','fontname','Times New Roman');
    set(gca,'fontsize',15);
    % xtickangle(45);
    ylim([58 86]);
    % legend('','Train','Test');
    title(gca,'MLP_2','FontWeight','normal');
    hold off;

    a=[84.31,0.62;84.19,0.56];
    subplot(1,3,3);
    figure(1),plot(1,82,'ko','color','white');hold on;
    figure(1),plot(2,a(1,1),' ko','MarkerSize',10,'MarkerFacecolor','black');
    figure(1),plot(3,a(2,1),'ko','MarkerSize',10,'MarkerFacecolor',[0.5,0.5,0.5]);
    figure(1),plot(4,82,'ko','color','white');
    er=errorbar([2,3],a(:,1),a(:,2),a(:,2));
    er.Color=[1 0 0];
    er.LineWidth=2;
    er.LineStyle='none';
    % XTick([1:1:2]);
    set(gca,'xtick',[1:1:4],'XTickLabel',{'','Train','Test'});
    ylabel('Accuracy [%]','fontsize',18,'fontweight','normal','fontname','Times New Roman');
    set(gca,'fontsize',15);
    % xtickangle(45);
    ylim([58 86]);
    % legend('','Train','Test');
    title(gca,'MLP_3','FontWeight','normal');
    hold off;
end
